PracticaAlberto/Controllers/CarrosCompraController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practica.Models;
using PracticaAlberto;

namespace PracticaAlberto.Controllers
{
    public class CarrosCompraController : Controller
    {
        private TiendaAlbertoEntities db = new TiendaAlbertoEntities();

        public ActionResult NumProductosCarroCompra(CarroCompra carroCompra)
        {
            return PartialView(carroCompra);
        }

        // GET: CarroCompra
        public ActionResult Index(CarroCompra carroCompra)
        {

            ViewData["importeTotal"] = getImporteTotal(carroCompra) ;
            return View(carroCompra);
        }

        private double getImporteTotal(List<Producto> listaProductos) {
            double importeTotal = 0;
            foreach (Producto producto in listaProductos)
            {
                importeTotal += producto.Precio;
            }
            return importeTotal;
        }


        public ActionResult AddProduct(int id, CarroCompra carroCompra)
        {
            if (ModelState.IsValid)
            {
                Producto producto = db.Productoes.Find(id);
                carroCompra.Add(producto);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (User.Identity.IsAuthenticated)
            {
                string loginCliente = User.Identity.Name;
                if (loginCliente == "admin@admin.es")
                {
                    return RedirectToAction("Index", "Productos");
                } else
                {
                    return RedirectToAction("IndexUsers", "Productos");
                }
            } else {
                return RedirectToAction("IndexUsers", "Productos");
            }
                
        }

        // GET: CarroCompra/Details/5
        public ActionResult DetailsProduct(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }


        //  GET: CarroCompra/Delete/5
        public ActionResult DeleteProduct(int id, CarroCompra carroCompra)
        {
            if (ModelState.IsValid)
            {
                Producto producto = carroCompra.Find(x => x.Id == id);
                carroCompra.Remove(producto);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return RedirectToAction("Index", "CarrosCompra");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PracticaAlberto/Controllers/WebAPI/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using PracticaAlberto;

namespace PracticaAlberto.Controllers.WebAPI
{
    public class PedidosController : ApiController
    {
        private TiendaAlbertoEntities db = new TiendaAlbertoEntities();

        public PedidosController()
        {
            db.Configuration.ProxyCreationEnabled = false;
        }

        // GET: api/Pedidos
        public IQueryable<Pedido> GetPedidoes()
        {
            return db.Pedidoes;
        }

        // GET: api/Pedidos/5
        [ResponseType(typeof(Pedido))]
        public IHttpActionResult GetPedido(string id)
        {
            Pedido pedido = db.Pedidoes.Find(id);
            if (pedido == null)
            {
                return NotFound();
            }

            return Ok(pedido);
        }

        // PUT: api/Pedidos/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutPedido(string id, Pedido pedido)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != pedido.Id)
            {
                return BadRequest();
            }

            db.Entry(pedido).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PedidoExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Pedidos
        [ResponseType(typeof(Pedido))]
        public IHttpActionResult PostPedido(Pedido pedido)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Pedidoes.Add(pedido);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateException)
            {
                if (PedidoExists(pedido.Id))
                {
                    return Conflict();
                }
                else
                {
                    throw;
                }
            }

            return CreatedAtRoute("DefaultApi", new { id = pedido.Id }, pedido);
        }

        // DELETE: api/Pedidos/5
        [ResponseType(typeof(Pedido))]
        public IHttpActionResult DeletePedido(string id)
        {
            Pedido pedido = db.Pedidoes.Find(id);
            if (pedido == null)
            {
                return NotFound();
            }

            db.Pedidoes.Remove(pedido);
            db.SaveChanges();

            return Ok(pedido);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool PedidoExists(string id)
        {
            return db.Pedidoes.Count(e => e.Id == id) > 0;
        }
    }
}

PracticaAlberto/Views/CarrosCompra/Create.cshtml
@model Producto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Id_Pedido, "FK_Id_Pedido", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FK_Id_Pedido", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FK_Id_Pedido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PracticaAlberto/Views/CarrosCompra/DetailsProduct.cshtml
@model Producto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)€
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @if (Model.Cantidad == 0)
                    {
                        <span class="label label-danger positionAbsolute">AGOTADO</span>
                    }
                    else if (Model.Cantidad >= 1 && Model.Cantidad <= 10)
                    {
                        <span class="label label-warning positionAbsolute">ÚLTIMAS UNIDADES</span>
                    }
                    else
                    {
                        //vacia aposta
                    }
                    @if (Model.Cantidad == 0)
                    {
                        <img class="img-circle imgProductoAgotado" widht="200" height="200" src="@(Model.Imagen)">
                    }
                    else if (Model.Cantidad >= 1 && Model.Cantidad <= 10)
                    {
                        <img class="img-circle imgProductoStockBajo" widht="200" height="200" src="@(Model.Imagen)">
                    }
                    else
                    {
                        <img class="img-circle imgNormal" widht="100" height="200" src="@(Model.Imagen)">
                    }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Volver", "Index", "CarrosCompra", null, new { @class = "btn botonMorado" })
</p>

PracticaAlberto/Views/CarrosCompra/Index.cshtml
@model IEnumerable<Producto>

@{
    ViewBag.Title = "Tu carrito:";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tu carrito:</h2>


@if (Model.Count() > 0)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                Acciones
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (item.Cantidad == 0)
                    {
                        <span class="label label-danger positionAbsolute">AGOTADO</span>
                    }
                    else if (item.Cantidad >= 1 && item.Cantidad <= 10)
                    {
                        <span class="label label-warning positionAbsolute">ÚLTIMAS UNIDADES</span>
                    }
                    else
                    {
                        //vacia aposta
                    }
                    @if (item.Cantidad == 0)
                {
                    <img class="img-circle imgProductoAgotado" widht="100" height="100" src="@(item.Imagen)">
                }
                else if (item.Cantidad >= 1 && item.Cantidad <= 10)
                {
                    <img class="img-circle imgProductoStockBajo" widht="100" height="100" src="@(item.Imagen)">
                }
                else
                {
                    <img class="img-circle imgNormal" widht="100" height="100" src="@(item.Imagen)">
                }
                </td>
                <td>
                    <span><strong>@(item.Nombre)</strong></span>
                </td>
                <td>
                    @Html.ActionLink("Detalles", "DetailsProduct", "CarrosCompra", new { id = item.Id }, new { @class = "btn botonAzul" })
                    @Html.ActionLink("Eliminar", "DeleteProduct", "CarrosCompra", new { id = item.Id }, new { @class = "btn botonRojo" })
                </td>
                <td>
                    <span class="precio">@(item.Precio)€</span>
                </td>
            </tr>
        }
    </table>
} else
{
    <h4 class="text-center">(Vacio)</h4>
}
    
@if (Model.Count() > 0)
{
        <hr class="separador" />
        <h4 style="text-align: right"><span style="margin-right: 20px;">Importe Total: </span><span><strong>@ViewData["importeTotal"]€</strong></span></h4>
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-md-offset-10">
                    @Html.ActionLink("Finalizar compra", "Create", "Pedidos", null, new { @class = "btn botonVerde negrita", style = "margin-top: 30px;" })
                </div>
            </div>
        </div>
}