PracticaAlberto/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using PracticaAlberto.Areas.HelpPage.ModelDescriptions;
using PracticaAlberto.Areas.HelpPage.Models;

namespace PracticaAlberto.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

PracticaAlberto/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practica.Models;
using PracticaAlberto;

namespace PracticaAlberto.Controllers
{
    public class ProductosController : Controller
    {
        private TiendaAlbertoEntities db = new TiendaAlbertoEntities();

        [Authorize(Users = "admin@admin.es")]
        // GET: Productos
        public ActionResult Index(CarroCompra carroCompra)
        {
            var productoes = db.Productoes;
            return View(productoes.ToList());
        }

        public ActionResult IndexUsers(CarroCompra carroCompra)
        {
            var productoes = db.Productoes;
            return View(productoes.ToList());
        }

        [Authorize(Users = "admin@admin.es")]
        // GET: Productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        public ActionResult DetailsUsers(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        [Authorize(Users = "admin@admin.es")]
        // GET: Productos/Create
        public ActionResult Create()
        {
            ViewBag.FK_Id_Pedido = new SelectList(db.Pedidoes, "Id", "Id");
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Users = "admin@admin.es")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Cantidad,Precio,Imagen")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Productoes.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(producto);
        }

        [Authorize(Users = "admin@admin.es")]
        // GET: Productos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Users = "admin@admin.es")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Cantidad,Precio,FK_Id_Pedido,Imagen")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(producto);
        }

        [Authorize(Users = "admin@admin.es")]
        // GET: Productos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Productos/Delete/5
        [Authorize(Users = "admin@admin.es")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Producto producto = db.Productoes.Find(id);
                db.Productoes.Remove(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View("Error");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PracticaAlberto/Views/Shared/NumProductosCarroCompra.cshtml
@model IEnumerable<Producto>

@Model.Count()

PracticaAlberto/Views/Shared/_Footer.cshtml
<footer>
    <p>&copy; @DateTime.Now.Year - Tienda Alberto - ASP.NET </p>
</footer>

PracticaAlberto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar")
    @Html.Partial("_PanelAdmin")
    <div class="container body-content">
        @RenderBody()
        <hr />
        @Html.Partial("_Footer")
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PracticaAlberto/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href='@Url.Action("IndexUsers", "Productos")'>
                <img src="~/Content/img/logo.png" height="40" />
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="btnOpcionMenu"><a>API</a></li>
                <li class="btnOpcionMenu"><a>Productos</a></li>
                <li class="btnOpcionMenu"><a>Pedidos</a></li>
                <li class="btnOpcionMenu"><a>Clientes</a></li>
                <li>
                    <a href='@Url.Action("Index", "CarrosCompra")' class="btnCarrito">
                        <span class="glyphicon glyphicon-shopping-cart gi-2x"></span> <span style="display: inline" class="badge alert-success">@{Html.RenderAction("NumProductosCarroCompra", "CarrosCompra");}</span>
                    </a>
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

PracticaAlberto/Views/Shared/_PanelAdmin.cshtml
@if (User.Identity.Name == "admin@admin.es")
{
    <div id="panelAdmin" class="collapse navbar-collapse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="margin-right: 31%"><h4 class="textoVerde"><strong><span class="glyphicon glyphicon-cog"></span> Panel de adminstación </strong></h4></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("API Doc", "Index", "Help", new { area = "" }, new { @class = "btnOpcionMenuAdmin botonVerdeOscuro" })</li>
                    <li>@Html.ActionLink("Productos", "Index", "Productos", new { area = "" }, new { @class = "btnOpcionMenuAdmin botonVerdeOscuro" })</li>
                    <li>@Html.ActionLink("Pedidos", "Index", "Pedidos", new { area = "" }, new { @class = "btnOpcionMenuAdmin botonVerdeOscuro" })</li>
                    <li>@Html.ActionLink("Clientes", "Index", "Clientes", new { area = "" }, new { @class = "btnOpcionMenuAdmin botonVerdeOscuro" })</li>
                </ul>
            </div>
        </div>
    </div>
}